apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
          limits:
            cpu: 350m
            memory: 600Mi
        envFrom:
        - configMapRef:
            name: config-worker
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-worker
data:
  JOB_TIME: "3000"
  EXPIRY_TIME: "10"
  WAIT_TIME: "3"
  RETRY_TIME: "500"
